{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "CRUD de cadastro de alunos",
    "description" : "Este recurso fornece operações CRUD para o cadastro de alunos",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/rafasantosbzr/desafio/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "https://sistema-escolar-generation.cyclic.cloud/",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : {
    "/alunos" : {
      "get" : {
        "summary" : "Lista todos os alunos",
        "responses" : {
          "200" : {
            "description" : "Sucesso"
          }
        }
      },
      "post" : {
        "summary" : "Cria um novo aluno",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Aluno"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Criado com sucesso"
          }
        }
      }
    },
    "/alunos/{id}" : {
      "get" : {
        "summary" : "Obtém um aluno por ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "$ref" : "#/components/schemas/Aluno"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Sucesso"
          }
        }
      },
      "put" : {
        "summary" : "Atualiza um aluno",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "$ref" : "#/components/schemas/Aluno"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Aluno"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Atualizado com sucesso"
          }
        }
      },
      "delete" : {
        "summary" : "Exclui um aluno",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "$ref" : "#/components/schemas/Aluno"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "Excluído com sucesso"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Aluno" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "nome" : {
            "type" : "string"
          },
          "idade" : {
            "type" : "string"
          },
          "primeira_nota" : {
            "type" : "string"
          },
          "segunda_nota" : {
            "type" : "string"
          },
          "professor_nome" : {
            "type" : "string"
          },
          "sala" : {
            "type" : "string"
          }
        }
      }
    }
  }
}